<?= Load::lib("html") ?>
<?= Load::lib("formato") ?>
<style type="text/css">
<!--
	h2{ color: #<?= SAM_COLOR1 ?>;}
	table.page_header {width: 100%; border: none; background-color: #FFF; color: #000; font-size: 18px; text-transform: uppercase; }
	.page_header table{ padding: 0px; margin: 0px; text-transform: uppercase;}
	table.informacion {width: 100%; border: none; background-color: #FFF; color: #000; font-size: 10px; text-transform: uppercase; }
	table.informacion td {border: 1px solid #333; padding: 5px; text-transform: uppercase; border: 1px solid #333;}
	table.page_footer {width: 100%; border: none; background-color: #<?= SAM_COLOR2 ?>; padding: 2mm; color: #FFF; font-size: 12px; text-transform: uppercase;}	
	.firma, div.standard .firma td{	border: 0px; }
	.formato1{
		background-color: #<?= SAM_COLOR1 ?>;
		color:#fff;		
		font-weight: bold;
		padding: 5px 2px;
		text-align: center;		
	}
	.formato2{
		background-color: #<?= SAM_COLOR3 ?>;
		color:#333;		
		font-weight: bold;	
		text-align: center;	
	}	
-->
</style>
<page backtop="60mm" backbottom="14mm" backleft="0mm" backright="0mm" style="font-size: 12pt">
	<page_header>
		<table border="0" class="page_header">
			<tr>
				<td width="100">
					<?= Html::imagen("http://www.ameca.gob.mx/intranet/img/ameca.jpg","H. Ayuntamiento de Ameca",100) ?>
				</td>
				<td width="475" align="center">
					<h2>FICHA INFORMATIVA<br />DE LA OBRA</h2>
				</td>
				<td width="100">
					<?= Html::imagen("http://www.ameca.gob.mx/intranet/img/titulo.jpg","Departamento de Obras Publicas",150) ?>
				</td>
			</tr>			
		</table>
		<br />
		<table cellpadding="0" cellspacing="0" class="informacion">
			<tr style="height: 0px;">
				<?php for($i=30;$i<=450; $i+=30){ echo '<td style="border: 0px; height: 0px;" height="0" width="30"></td>'; } ?>
			</tr>
			<tr>
				<td class="formato1" colspan="2">
					OBRA:
				</td>
				<td width="580" colspan="13">
					<?= $obra -> nombre ?>
				</td>
			</tr>
			<tr>
				<td class="formato1" colspan="2">
					CÓDIGO:
				</td>
				<td colspan="3">
					<?= $obra -> codigo ?>
				</td>
				<td class="formato1" colspan="2">
					ACTA:
				</td>
				<td colspan="3">
					<?//= $obra -> acta_id ?>
				</td>
				<td class="formato1" colspan="2">
					LUGAR:
				</td>
				<td colspan="3">
					<?= $obra -> localidad() -> nombre ?>
				</td>
			</tr>
			<tr>
				<td class="formato1" colspan="3">
					TIPO DE OBRA:
				</td>
				<td colspan="7">
					<?= $obra -> tipoobra() -> nombre ?>
				</td>
				<td class="formato1" colspan="2">
					ESTADO:
				</td>
				<td colspan="3">
					<?= $obra -> estado ?>
				</td>
			</tr>
		</table>				
	</page_header>
	<page_footer>
		<table class="page_footer">
			<tr>
				<td style="width: 50%; text-align: left">
					<?= SAM_ADMINISTRACION ?><br />
					PÁGINA [[page_cu]]
				</td>				
				<td style="width: 50%; text-align: right">
					<?= AUTOR_URL ?><br />
					Impreso desde SAM <?= date('d/m/Y H:i') ?> Hrs.
				</td>
			</tr>			
		</table>
	</page_footer>
	
	<table cellpadding="0" cellspacing="0" class="informacion">
		<tr style="height: 0px;">
			<?php for($i=30;$i<=450; $i+=30){ echo '<td style="border: 0px; height: 0px;" height="0" width="30"></td>'; } ?>
		</tr>			
		<?php		
		if($requisicion){ ?> 		
		<tr>
			<td class="formato1" colspan="2">CONCEPTO</td>
			<td colspan="6"><?= $requisicion -> concepto ?></td>
			<td class="formato1" colspan="2">FECHA</td>
			<td colspan="5"><?= Formato::fechaExtendida($requisicion -> fecha) ?></td>				
		</tr>
		<tr>
			<td class="formato1" colspan="2">ELABORADO POR</td>
			<td colspan="6"><?= $requisicion -> elaboro() -> nombre ?></td>
			<td class="formato1" colspan="2">ASIGNADO A</td>
			<td colspan="5"><?= $requisicion -> supervisor() -> nombre ?></td>				
		</tr>
	</table>
	<table cellpadding="0" cellspacing="0" class="informacion">		
		<thead>			
		<tr style="height: 0px;">
			<?php for($i=30;$i<=450; $i+=30){ echo '<td style="border: 0px; height: 0px;" height="0" width="30"></td>'; } ?>
		</tr>
		<tr>			
			<td class="formato1" colspan="9">PRODUCTO</td>
			<td class="formato1" colspan="2">UNIDAD / MEDIDA</td>
			<td class="formato1" colspan="2">CANTIDAD</td>
			<td class="formato1" colspan="2">ASIGNADO</td>			
		</tr>		
		</thead>
		<?php
		$conceptos = IobrasConceptorequisicion::reporte('requisicion_id = '.$requisicion -> id); 
		if($conceptos){
			echo '<tbody>'; 
			$cont = 1;
			foreach ($conceptos as $concepto) { ?>
		<tr>			
			<td colspan="9"><?= $concepto -> insumo() -> nombre ?></td>
			<td colspan="2"><?= $concepto -> insumo() -> medida ?></td>
			<td colspan="2" style="text-align: center;"><?= $concepto -> cantidad ?></td>
			<td colspan="2" style="text-align: center;"><?= $concepto -> asignado ?></td>
		</tr>
		<?php
				$cont++;
			}
			echo '</tbody>';
		} ?>		
	</table>
	<br /><br /><br />
	<br /><br /><br />
	<table cellpadding="0" cellspacing="0" class="firma">
		<tr>
			<td width="450"></td>
			<td style="border-bottom: 2px solid #333; width: 150px"></td>				
		</tr>
		<tr>
			<td></td>
			<td style="font-weight: bold; font-size: 12px; text-align: center;"><?= $requisicion -> autorizo() ? $requisicion -> autorizo() -> nombre : 'SIN AUTORIZACIÓN' ?></td>				
		</tr>
		<tr>
			<td></td>
			<td style="font-size: 10px; text-align: center;"><?= $requisicion -> autorizo() ? $requisicion -> autorizo() -> puesto : 'POR NINGUN EMPLEADO' ?></td>
		</tr>
	</table>
	<?php } ?>
</page>
