<?= Load::lib("amecasoft") ?>
<?php $obra = Obra::consultar($obra); ?>
<table>
    <tr>
        <td class="formato1" width="365" height="25" ><br/>
            <center><?= View::partial("menuObra",false,array("obra" => $obra -> id,"opcion" => "informacion")) ?></center>
        </td>
    </tr>
    <tr>
    	<td class="formato2"><br />
            <center><?= View::partial("menuInformacionObra",false,array("obra" => $obra -> id,"opcion" => "archivos")) ?></center>
    	</td>
    </tr>
</table>

<?= Formulario::inicioAjax("obras/adjuntar","opciones") ?>
<input type="hidden" name="id" value="<?= $obra -> id ?>" />
<table class="formulario" height="895">
    <tr>
        <td width="350" id="contenido" align="center" valign="top">
        	<br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="350" align="left">
                        <h2 id="titulo">
                        	Archivos Adjuntos
                        </h2>
                        <span id="subtitulo">
                            Generalmente serán los documentos que complementan la Obra.
                        </span>
                        <br /><br />
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>                                       
                <tr>
			    	<td colspan="7" height="10">
			        	<?php $archivos = OArchivo::reporte("obras_id=".$obra -> id); ?>
			            <?php if($archivos){ ?>
				        	<table border="0">
				            	<?php foreach($archivos as $archivo){ ?>
				            		<?= tr_color("#CCCCCC","#DDDDDD") ?>
				                    	<td style="padding: 5px;"><?= Acl::link("files/archivos_obras/".$archivo -> archivo,Html::imagen(iconoArchivo($archivo -> archivo),tipoArchivo($archivo -> archivo),20,20),"target: blank") ?></td>
					                    <td style="padding: 5px;" width="260"><?= strtoupper($archivo -> nombre) ?></td>
					                    <?php if($obra -> estado != "TERMINADA"){ ?>
					                    	<td style="padding: 5px;"><?= Acl::linkAjaxConfirmado("obras/desadjuntar/".$archivo -> id,Html::imagen("icons/close.png","Eliminar Archivo",20,20),"opciones","Estas seguro que deseas eliminar el Archivo?") ?></td>
					                    <?php } ?>
									</tr>
				            	<?php } ?>
				            	<?php if(count($archivos)>1){ ?>
				                	<tr>
				                    	<td colspan="3" align="right" style="padding: 10px 0px 10px 10px;"><b><?= Acl::link("obras/descargar/".$obra -> id,"DESCARGAR TODOS LOS ARCHIVOS","class: boton2") ?></b></td>
				                    </tr>
				            	<?php } ?>
							</table>
				        <?php } else { ?>
				        	<center><b>NO SE HAN AGREGADO ARCHIVOS</b></center>
				        <?php } ?>
					</td>
			   	</tr>
			   	<?php if(Acl::tienePermiso(Session::get("usuario_id"),"obras","programar") && $obra -> estado != "TERMINADA"){ ?>
                <tr>
                    <td colspan="7" height="10"><br /><hr /><br/></td>
                </tr>
                <tr>
                    <td colspan="7" height="10" align="center" bgcolor="DDDDDD" style="padding: 5px;">
						<table border="0">
							<tr>
			                    <td>
			                        <div id="texto_arriba">Identificador del Archivo <span id="asterisco">*</span></div>
			                        <?= Formulario::mayusculas("nombre","","class: tmediano","style: width: 300px;","validate: required:true") ?>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>                                       
			                <tr>
			                    <td>
			                        <div id="texto_arriba">Archivo a Adjuntar <span id="asterisco">*</span></div>
			                        <?= Formulario::archivo("archivo","","class: tmediano","style: width: 300px;","validate: required:true") ?>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>
			                <tr>
			                    <td height="25" align="right">
			                        <?= Formulario::submit("Adjuntar Archivo","class: boton1") ?>
			                    </td>
			                </tr>
						</table>
					</td>
                </tr>
                <?php } ?>
            </table>
            <br />    
        </td>
    </tr>
</table>
<?= Formulario::fin() ?>
</div>