<?= Load::lib("amecasoft") ?>
<?php $obra = Obra::consultar($obra); ?>
<table>
    <tr>
        <td class="formato1" width="365" height="25" ><br/>
            <center><?= View::partial("menuObra",false,array("obra" => $obra -> id,"opcion" => "tareas")) ?></center>
        </td>
    </tr>
    <tr>
    	<td class="formato2"><br />
            <center><?= View::partial("menuTareasObra",false,array("obra" => $obra -> id,"opcion" => "pendientes")) ?></center>
    	</td>
    </tr>
</table>
<?= Formulario::inicioAjax("obras/asignarTarea","opciones") ?>
<input type="hidden" name="id" value="<?= $obra -> id ?>" />
<table class="formulario" height="895">
    <tr>
        <td width="350" id="contenido" align="center" valign="top">
            <br />
            <div id="tareas">
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="320"align="left">
                        <h2 id="titulo">
                        	Tareas Pendientes
                        </h2>
                        <span id="subtitulo">
                            Las tareas pendientes a realizar son mostradas a continuación..
                        </span>
                        <br /><br />
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>                                       
                <tr>
			    	<td colspan="7" height="10" align="center">
			    		<?php $tareas = OTarea::reporte("obras_id=".$obra -> id." AND estado = 'KO'"); ?>
			            <?php if($tareas){ ?>
				        	<table border="0">
				            	<?php foreach($tareas as $tarea){ ?>
				            		<?= tr_color("#CCCCCC","#DDDDDD") ?>
				                    	<td style="padding: 5px;" width="285"><?= strtoupper($tarea -> nombre) ?></td>
					                    <td style="padding: 5px;"><?= Acl::linkAjax("obras/consultarTarea/".$tarea -> id,Html::imagen("icons/preview.png","Consultar Tarea",20,20),"tareas") ?></td>
									</tr>
				            	<?php } ?>
							</table>
				        <?php } else { echo "NO EXISTEN TAREAS REGISTRADAS"; } ?>
					</td>
			   	</tr>
                <?php if(Acl::tienePermiso(Session::get("usuario_id"),"obras","asignarTarea") && $obra -> estado != "TERMINADA"){ ?>
                <tr>
                    <td colspan="7" height="10" align="center">
                    	<br /><hr /><br/>
                        <b>TAREA NUEVA</b>
                        <br /><br/>
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10" align="center" bgcolor="DDDDDD" style="padding: 5px;">
						<table border="0">
							<tr>
			                    <td colspan="2">
			                    	<div id="texto_arriba">&nbsp;</div>
			                        <?= Formulario::autocompleteModelo("empleado",Empleado::reporte(),"nombre","","class: tmediano","style: width: 300px;","validate: required:true") ?>
			                        <div id="texto_abajo">Empleado<span id="asterisco">*</span></div>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>                                       
			                <tr>
			                    <td colspan="2">
			                        <?= Formulario::mayusculas("nombre","","class: tmediano","style: width: 300px;","validate: required:true") ?>
			                        <div id="texto_abajo">Nombre de la Tarea<span id="asterisco">*</span></div>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>                                       
			                <tr>
			                    <td colspan="2">
			                        <?= Formulario::textarea("descripcion","","style: width: 307px; height: 70px;","validate: required:true") ?>
			                        <div id="texto_abajo">Descripción de Actividades<span id="asterisco">*</span></div>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>
			                <tr>
			                    <td>
			                        <?= Formulario::fecha("creacion","","dd/mm/yy",false,0,"class: fchico","style: width: 142px;","validate: required:true") ?>
			                        <div id="texto_abajo">Fecha Asignación<span id="asterisco">*</span></div>
			                    </td>
			                    <td>
			                        <?= Formulario::fecha("limite","","dd/mm/yy",0,false,"class: fchico","style: width: 142px;","validate: required:true") ?>
			                        <div id="texto_abajo">Fecha Límite<span id="asterisco">*</span></div>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>
			                <tr>
			                    <td height="25" align="right" colspan="2">
			                        <?= Formulario::submit("Asignar Tarea","class: boton1") ?>
			                    </td>
			                </tr>
						</table>
						</div>
					</td>
                </tr>
                <?php } ?>
            </table>
            <br />    
        </td>
    </tr>
</table>
<?= Formulario::fin() ?>
</div>