<?= Load::lib("amecasoft") ?>
<?= Formulario::inicioAjax($controller_name."/programar","opciones") ?>
<input type="hidden" name="id" value="<?= $proyecto -> id ?>" />
<table class="formulario" height="940">
    <tr>
		<td class="formato1" height="45">
			<?= View::partial("menuProyecto",false,array("proyecto" => $proyecto -> id,"opcion" => "programas")) ?>
		</td>
	</tr>
    <tr>
        <td class="formato2" height="50">
            &nbsp;
        </td>
    </tr>
    <tr>
        <td width="340" id="contenido" align="center" valign="top">
            <br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="320"align="left">
                        <h2 id="titulo">
                        	Programas
                        </h2>
                        <span id="subtitulo">
                            Los programas aportan fondos a las obras y proyectos.
                        </span>
                        <br /><br />
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>                                       
                <tr>
			    	<td colspan="7" height="10">
			        	<?php $programas = $proyecto -> programas(); ?>
			            <?php if($programas){ ?>
				        	<table border="0">
				            	<?php foreach($programas as $programa){ ?>
				            		<?= tr_color("#CCCCCC","#DDDDDD") ?>
				                    	<td style="padding: 5px;" width="285"><?= strtoupper($programa -> programa() -> nombre) ?></td>
					                    <td style="padding: 5px;"><?= Acl::linkAjaxConfirmado($controller_name."/desprogramar/".$programa -> id,Html::imagen("icons/close.png","Eliminar Programa",20,20),"opciones","Estas seguro que deseas eliminar el Programa?") ?></td>
									</tr>
				            	<?php } ?>
							</table>
				        <?php } else { ?>
				        	<center><b>NO SE HAN AGREGADO PROGRAMAS</b></center>
				        <?php } ?>
					</td>
			   	</tr>
                <tr>
                    <td colspan="7" height="10"><br /><hr /><br/></td>
                </tr>
                <tr>
                    <td colspan="7" height="10" align="center" bgcolor="DDDDDD" style="padding: 5px;">
						<table border="0">
							<tr>
			                    <td>
			                        <div id="texto_arriba">Selecciona un Programa <span id="asterisco">*</span></div>
			                        <?= Formulario::selectModelo("programa",PPrograma::reporteDisponibles($proyecto -> id),"nombre","id","","class: smediano","style: width: 320px;","validate: required:true") ?>
			                    </td>
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>
			                <tr>
			                    <td height="25" align="right">
			                        <?= Formulario::submit("Agregar Programa","class: boton1") ?>
			                    </td>
			                </tr>
						</table>
					</td>
                </tr>
            </table>
            <br />    
        </td>
    </tr>
</table>
<?= Formulario::fin() ?>
</div>