<?= Load::lib("amecasoft") ?>

<?= $contratista ? Formulario::inicio($controller_name."/modificarContratista") : Formulario::inicio($controller_name."/registrarContratista") ?>
<input type="hidden" name="id" value="<?= $id ?>" />
<table class="formulario">
    <tr>
        <th id="mensaje" width="1024" height="25" >
            <?= $mensaje; ?>&nbsp;
        </th>
    </tr>
    <tr>
        <td width="1024" height="205" id="contenido" align="center">
            <div align="right">
            	<?= Formulario::cancelar("Regresar",$controller_name."/contratistas","class: boton1") ?>
            </div>
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="1000"align="left">
                        <h2 id="titulo">
                        	<?= $contratista ? "Modificación de la Contratista" : "Registro de Nueva Contratista" ?>
                        </h2>
                        <span id="subtitulo">
                            Los campos marcados con <span id="asterisco">*</span> son obligatorios y no se podrá almacenar el registro hasta que esten completos.
                        </span>
                        <br /><br />
                        <hr />
                        <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>
                <tr>
                    <td colspan="3">
                    	<div id="texto_arriba">Nombre del Contratista <?= Formulario::asterisco() ?></div>
                        <?= Formulario::mayusculas("nombre",$contratista ? $contratista -> nombre : "","class: tmediano","validate: required:true") ?>
                        <div id="texto_abajo">&nbsp;</div>   
                    </td>
                    <td width="20"></td>  
                    <td>
                        <div id="texto_arriba">Datos de Contacto</div>
                        <?= Formulario::numerico("telefono",$contratista ? $contratista -> telefono : "","class: tchico") ?>
                        <div id="texto_abajo">Teléfono</div>    
                    </td>
                    <td width="20"></td>
                    <td>
                        <div id="texto_arriba">&nbsp;</div>
                        <?= Formulario::numerico("celular",$contratista ? $contratista -> celular : "","class: tchico") ?>
                        <div id="texto_abajo">Celular</div>    
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>
                <tr>
                    <td width="1000" height="25" colspan="7" align="right">
                        <?= Formulario::cancelar("Cancelar",$controller_name."/contratistas","class: boton3") ?>
                        <?= $contratista ? Acl::linkConfirmado($controller_name."/eliminarContratista/".$contratista -> id,"Eliminar","Estas seguro que deseas eliminar la contratista?","class: boton2") : "" ?>
                    	<?= $contratista ? Formulario::submit("Modificar","class: boton1") : Formulario::submit("Registrar","class: boton1") ?>
                    </td>
                </tr>
            </table>
            <br />    
        </td>
    </tr>
</table>
<?= Formulario::fin() ?>