<?php  
if($width AND $height){
	Session::set('pantalla',$width);
	Session::set('alto',$height);
}else{ 
	echo "<script language='javascript'>\n"; 
	echo " location.href=\"".$controller_name."/".$action_name."/\" + screen.width + \"/\" + screen.height;\n";	
	echo "</script>\n"; 
	exit(); 
} 
?>
<?= Load::lib("amecasoft")
?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="es">
	<head>
		<meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
		<title>Sistema de Administracion Municipal <?= SAM_MUNICIPIO ?> <?= SAM_ESTADO ?></title>		
		<link rel="stylesheet" type="text/css" href="/intranet/css/estilo.css"/>
		<link rel="stylesheet" type="text/css" href="/intranet/css/<?= SAM_TEMPLATE?>.css"/>
		<link rel="stylesheet" type="text/css" href="/intranet/css/style.css"/>		
	</head>
	<body>
		<div class="inicio">
		<div class='cabecera'>
			Sistema de Administración Municipal - Ameca Jalisco
		</div>
		<div id="contenido">
			<?= Formulario::inicio("seguridad/login","name: inicioSession"); ?>
			<table border="0" cellpadding='0' cellspacing='0'>
				<tr>
					<th colspan="2">
						<?php
							if (Session::get('mensajeE') != '') {
								echo Session::get('mensajeE');
								echo '<br /><br />';
								Session::set('mensajeE', '');
							}else{
								echo 'INICIO DE SESIÓN';
							}	
							
						?>
					</th>
				</tr>
				<tr>
					<td width="100"><b>Usuario: </b></td>
					<td><b><?= Formulario::texto("usuario", "", "style: width: 150px;");?></b></td>
				</tr>
				<tr>
					<td colspan="2">&nbsp;</td>
				</tr>
				<tr>
					<td><b>Contraseña: </b></td>
					<td><?= Formulario::password("password", "", "style: width: 150px;");?></td>
				</tr>
				<tr>
					<td colspan="2">&nbsp;</td>
				</tr>
				<tr>
					<td colspan="2" align="right"><?= Formulario::submit("Ingresar","style: height: 30px; width: 100px;","onclick: ancho();")
					?></td>
				</tr>
			</table>
			<?= Formulario::fin() ?>
		</div>
		<div class='pie'>
			&copy; <a href='<?= AUTOR_URL ?>' target='_blank'><?= AUTOR_NOMBRE ?></a>
		</div>
		</div>
	</body>
</html>