<?= Load::lib("amecasoft") ?>
<div id="requisicion<?= $requisicion ?>">
<?php $requisicion = Requisicion::consultar($requisicion); ?>
<?php $productos = Insumo::reporte(); ?>
<?php
	if($productos) foreach($productos as $producto){
		$producto -> nombre = $producto -> nombre . " {".$producto -> medida."}";
	}
?>
<table class="formulario" height="580">
    <tr>
        <td width="780" id="contenido" align="center" valign="top">
            <br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="780"align="left">
                        <h2 id="titulo">
                        	Información de la Requisición (<?= fechaMediana($requisicion -> fecha_at) ?>)
                        </h2>
                        <span id="subtitulo">
                            A continuación se muestran los detalles o conceptos que cubre la requisición.
                        </span>
                        <br /><br />
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>                                       
                <tr>
			    	<td colspan="7" height="10">
			    	<?php if($requisicion -> estado == "ENVIADA"){ ?>
			    		<?= Formulario::inicio("obras/autorizarRequisicion/".$requisicion -> id); ?>
			    		<?= Formulario::oculto("requisicion",$requisicion -> id); ?>
			    	<?php } ?>			    		
			        	<?php $conceptos = $requisicion -> conceptos(); ?>
			            <?php if($conceptos){ ?>
				        	<table border="0">
				        		<tr>
				        			<th width="100" height="25">Cantidad</th>
				        			<th width="400">Concepto</th>
				        			<th width="120">Precio Unitario</th>
				        			<th width="120">Importe</th>
				        			<?php if($requisicion -> estado == "NUEVA"){ ?>
				        				<th width="50"></th>
				        			<?php } ?>
				        		</tr>
				            	<?php $i=0; foreach($conceptos as $concepto){ $i++; ?>
				            		<?= tr_color("#CCCCCC","#DDDDDD") ?>
				                    	<td height="25" align="center" style="padding: 5px;">
				                    		<?php if($requisicion -> estado == "ENVIADA"){ ?>
				                    			<?= Formulario::numerico("cantidad".$concepto -> id,$concepto -> cantidad,"style: width: 75px; text-align: center;","onchange: document.getElementById('importe".$concepto -> id."').value = document.getElementById('cantidad".$concepto -> id."').value * (document.getElementById('precio".$concepto -> id."').value.substring(2)); document.getElementById('importe".$concepto -> id."').focus(); document.getElementById('enviar".$requisicion -> id."').focus();") ?>
				                    		<?php } else { ?>
				                    			<?= $concepto -> cantidad ?>
				                    		<?php } ?>
				                    	</td>
					                    <td align="center" style="padding: 5px;"><?= $concepto -> insumo() -> medida ?> de <?= $concepto -> insumo() -> nombre ?></td>
					                    <td align="center" style="padding: 5px;">
				                    		<?php if($requisicion -> estado == "ENVIADA"){ ?>
				                    			<?= Formulario::dinero("precio".$concepto -> id,$concepto -> precio,"style: width: 90px; text-align: center; background-color: #EEE;","readonly: readonly") ?>
				                    		<?php } else { ?>
				                    			$ <?= number_format($concepto -> precio,2) ?>
				                    		<?php } ?>
					                    </td>
					                    <td align="center" style="padding: 5px;">
					                    	<?php if($requisicion -> estado == "ENVIADA"){ ?>
				                    			<?= Formulario::dinero("importe".$concepto -> id,$concepto -> cantidad * $concepto -> precio,"style: width: 90px; text-align: center; background-color: #EEE;","readonly: readonly") ?>
				                    		<?php } else { ?>
				                    			$ <?= number_format($concepto -> cantidad * $concepto -> precio,2) ?>
				                    		<?php } ?>
					                    </td>
					                    <?php if($requisicion -> estado == "NUEVA"){ ?>
					                    	<td align="center">
					                    		<?= Acl::linkAjax("obras/eliminarConceptoRequisicion/".$concepto -> id,Html::imagen("miniconos/delete.png","Eliminar Concepto",18,18),"requisicion".$requisicion -> id) ?>
					                    	</td>
					                    <?php } ?>
									</tr>
				            	<?php } ?>
							</table>
				        <?php } else { ?>
				        	<center><b>NO SE HAN AGREGADO CONCEPTOS A LA REQUISICION</b></center>
				        <?php } ?>
				        <center>
				        <?php if($requisicion -> estado == "NUEVA"){ ?>
				        <br />
				        <?= Formulario::inicioAjax("obras/agregarConceptoRequisicion","requisicion".$requisicion -> id); ?>
				        <input type="hidden" name="id" value="<?= $requisicion -> id ?>" />
				        <table border="0">
				        	<tr>
				        		<td>
				        			<div id="texto_arriba"></div>
				        			<?= Formulario::numerico("cantidad".$requisicion -> id,"","style: width: 125px;","onchange: document.getElementById('importe".$requisicion -> id."').value = document.getElementById('cantidad".$requisicion -> id."').value * (document.getElementById('precio".$requisicion -> id."').value.substring(2)); document.getElementById('importe".$requisicion -> id."').focus(); document.getElementById('producto".$requisicion -> id."').focus();","validate: required:true") ?>
				        			<div id="texto_abajo">Cantidad</div>
				        		</td>
				        		<td>
				        			<div id="texto_arriba"></div>
				        			<?= Formulario::autocompleteModelo("producto".$requisicion -> id,$productos,"nombre","","style: width: 300px;","validate: required:true") ?>
				        			<div id="texto_abajo">Concepto</div>
				        		</td>
				        		<td>
				        			<div id="texto_arriba"></div>
				        			<?= Formulario::dinero("precio".$requisicion -> id,"","style: width: 125px;","onchange: document.getElementById('importe".$requisicion -> id."').value = document.getElementById('cantidad".$requisicion -> id."').value * document.getElementById('precio".$requisicion -> id."').value; document.getElementById('importe".$requisicion -> id."').focus(); this.focus();","validate: required:true"); ?>
				        			<div id="texto_abajo">Precio Unitario</div>
				        		</td>
				        		<td>
				        			<div id="texto_arriba"></div>
				        			<?= Formulario::dinero("importe".$requisicion -> id,"","style: width: 125px;","readonly: readonly") ?>
				        			<div id="texto_abajo">Importe</div>
				        		</td>
				        	</tr>
				        	<tr>
				        		<td colspan="4" align="right">
				        			<div id="texto_arriba"></div>
				        			<?= Formulario::submit("Agregar Concepto","class: boton3") ?>	
				        			<div id="texto_abajo"></div>
				        		</td>
				        	</tr>
				        </table>
				        <?= Formulario::fin(); ?>
				        </center>
				        <?php } ?>
				        <br /><hr /><br/>
				        <?php if($requisicion -> estado == "NUEVA"){ ?>
				        	<div align="right">
				        	<?php if($requisicion -> nconceptos() > 0){ ?>
				        		<?= Acl::link("obras/terminarRequisicion/".$requisicion -> id,"Enviar Requisición","class: boton1","style: color:#EEE;") ?>
				        	<?php } ?>
				        	</div>
				        <?php } ?>
				        <?php if($requisicion -> estado == "ENVIADA"){ ?>
				        	<div align="right">
				        	<?php if($requisicion -> nconceptos() > 0){ ?>
				        		<?= Formulario::submit("Autorizar Requisicion","class: boton1","id: enviar".$requisicion -> id,"style: color:#EEE;") ?>
				        	<?php } ?>
				        	</div>
				        	<?= Formulario::fin(); ?>
				        <?php } ?>
				        <?php if($requisicion -> estado == "AUTORIZADA"){ ?>
				        	<div align="right">
				        	<?php if($requisicion -> nconceptos() > 0){ ?>
				        		<?= Acl::link("pdf/requisicion/".$requisicion -> id,"Formato PDF","class: boton1","style: color:#EEE;","target: _blank") ?>
				        	<?php } ?>
				        	</div>
				        <?php } ?>
					</td>
			   	</tr>
			</table>
		</td>
	</tr>
</table>
</div>