<?= Load::lib("amecasoft") ?>
<?php $titulo = "Listado de Categorías" ?>
<?php $subtitulo = "Las categorías sirven para determinar el puesto y salario de cada trabajador agregado a la nomina." ?>
<?php $modelo = "Categoría"; ?>
<?php 
    $titulos = array(
        "id" => "Id|100",
        "nombre" => "Nombre|500",
    	"salario" => "Salario Diario|150",
    );
?>

<table class="formulario">
    <tr>
        <th width="1024" height="25" id="mensaje">
            <?= $mensaje; ?>&nbsp;
        </th>
    </tr>
    <tr>
        <td width="1024" height="205" id="contenido" align="center">
            <br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" style="width: 1000px;" align="left">
                    	<?= Formulario::inicio("nominas/buscarCategoria") ?>
                        <table border="0" width="1000" >
                            <tr>
                                <td>
                                    <h2 id="titulo">
                                        <?= $titulo ?>
                                    </h2>
                                    <span id="subtitulo">
                                        <?= $subtitulo ?>
                                    </span>
                                    <br /><br />
                                </td>
                                <td width="25">
                                
                                </td>
                                <td width="300">
                                	
                                </td>
                                <td width="50">
                                	
                                </td>
                            </tr>
                        </table>
                        <?= Formulario::fin() ?>
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>
                <tr height="25">
                    <td colspan="7" style="width: 1000px;" align="center">
                        
                            <table class="formulario" width="1000">
                                <tr id="encabezado">
                                    <?php if($titulos) foreach($titulos as $field => $value){ $titulo = substr($value,0,strpos($value,"|")); $tam = substr($value,strpos($value,"|")+1); ?>
							            <th width="<?= $tam ?>">
							                <?= Html::link($controller_name."/categorias/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1", $titulo,"principal","style: color: #000; text-decoration: none;") ?>
							                <?php 
							                    if($campo == $field){
							                        if($orden=="ASC"){
							                            echo Html::link($controller_name."/categorias/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1",Html::imagen("decendente.png","Ordenar Ascendente",12,12),"principal","style: color: #000; text-decoration: none;");
							                        }
							                        else{
							                            echo Html::link($controller_name."/categorias/".$filtro."/".$field."-".($campo==$field ? $orden : "ASC")."/1",Html::imagen("ascendente.png","Ordenar Descendente",12,12),"principal","style: color: #000; text-decoration: none;");
							                        }
							                    }
							                ?>
							            </th>
						            <?php } ?>									
						            <th height="25" width="25" align="center" colspan="2">
                                    	<?= Acl::link("nominas/registroCategoria",Html::imagen("icons/add.png","Registrar Categoria",15,15)) ?>
                                    </th>
                                </tr>
                        <?php if($registros){ ?>
                            <?php $i=0; foreach($registros as $registro){ $i++; if($i%2==0) $x = "fila1"; else $x="fila2"; ?>
                                <tr id="<?= $x ?>">
                                    <td height="25" width="50" align="center">
                                        <?= formatoNumero($registro -> id,4) ?>
                                    </td>
                                    <td height="25" width="275" align="center">
                                        <?= $registro -> nombre ?>
                                    </td>
                                    <td height="25" width="50" align="center">
                                        $<?= number_format($registro -> salario,2) ?>
                                    </td>
                                    <td width="25" align="center">
                                    	<?= Acl::link("nominas/consultaCategoria/".$registro -> id,Html::imagen("icons/preview.png","Consultar Categoria",20,20)) ?>
                                    </td>
                                    <td width="25" align="center">
                                    	<?= Acl::linkConfirmado("nominas/eliminarCategoria/".$registro -> id,Html::imagen("icons/close.png","Eliminar Categoria",20,20),"Estas seguro que deseas eliminar la categoria de empleado?") ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                        <?php if($registros){ ?>
                                <tr>
                                    <th colspan="6" align="right" height="30">
                                        <?php if($nps > 1){ ?>
                                        <table border="0">
                                            <tr>
                                                <?php if($np > 1){ ?>
                                                    <td id="paginador">
                                                    	<?= Html::link($controller_name."/categorias/".$filtro."/".$campo."-".($orden == "ASC" ? "DESC" : "ASC")."/".($np - 1),"<") ?>
                                                    </td>
                                                <?php } ?>
                                                <?php for($i=1;$i<=$nps;$i++){ ?>
                                                    <?php if($np == $i){ ?>
                                                        <td id="paginador2">
                                                        	<?= Html::link($controller_name."/categorias/".$filtro."/".$campo."-".($orden == "ASC" ? "DESC" : "ASC")."/".$i,$i) ?>
                                                        </td>
                                                    <?php } else{ ?>
                                                        <td id="paginador">
                                                        	<?= Html::link($controller_name."/categorias/".$filtro."/".$campo."-".($orden == "ASC" ? "DESC" : "ASC")."/".$i,$i) ?>
                                                        </td>
                                                    <?php } ?>
                                                <?php } ?>
                                                <?php if($np < $nps){ ?>
                                                    <td id="paginador">
                                                    	<?= Html::link($controller_name."/categorias/".$filtro."/".$campo."-".($orden == "ASC" ? "DESC" : "ASC")."/".($np + 1),">") ?>
                                                    </td>
                                                <?php } ?>
                                                <td width="2"></td>
                                            </tr>
                                        </table>
                                        <?php } ?>
                                    </th>
                                </tr>
                            </table>
                        <?php } ?>
                    </td>
                </tr>
            </table>
            <br />
            <b>Número de Registros: <?= $nregistros; ?></b>
            <br /><br />     
        </td>
    </tr>
</table>