<?= Load::lib("amecasoft") ?>
<?= Formulario::inicio("nominas/registrar") ?>
<table class="formulario">
    <tr>
        <th id="mensaje" width="1024" height="25" >
            <?= $mensaje; ?>&nbsp;
        </th>
    </tr>
    <tr>
        <td width="1024" height="205" id="contenido" align="center">
            <div align="right"><?= Formulario::cancelar("Regresar","nominas/reporte","class: boton1"); ?></div>
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="1000"align="left">
                        <h2 id="titulo">
                            Registro de Nueva Nomina
                        </h2>
                        <span id="subtitulo">
                            Los campos marcados con <span id="asterisco">*</span> son obligatorios y no se podrá almacenar el registro hasta que esten completos.
                        </span>
                        <br /><br />
                        <hr />
                        <br />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>
                <tr>
                	<td>
                        <?= Formulario::selectModelo("obra",$obras,"nombre","id","","class: smediano","validate: required:true") ?>
                        <div id="texto_abajo">Obra a la que Pertenece <span id="asterisco">*</span></div>    
                    </td>
                    <td width="20"></td>
                    <td colspan="3">
                        <?= Formulario::fecha("inicio","","dd/mm/yy",false,false,"class: tchico","validate: required:true") ?>
                        <div id="texto_abajo">Fecha Inicio <span id="asterisco">*</span></div> 
                    </td>
                    <td width="20"></td>
                    <td colspan="3">
                        <?= Formulario::fecha("fin","","dd/mm/yy",false,false,"class: tchico","validate: required:true") ?>
                        <div id="texto_abajo">Fecha Fin <span id="asterisco">*</span></div> 
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="30"></td>
                </tr>
                <tr>
                    <td width="1000" height="25" colspan="7" align="right">
                    	<?= Formulario::cancelar("Cancelar","nominas/empleados","class: boton3") ?>
                    	<?= Formulario::submit("Registrar","class: boton1") ?>
                    </td>
                </tr>
            </table>
            <br />    
        </td>
    </tr>
</table>
