<?= Load::lib("amecasoft") ?>
<?php
	$nobras = Obra::total($sql);
	$obras = Obra::reporte($sql);
?>
<?php $titulo = "Listado de Obras" ?>
<?php $subtitulo = "Las Obras Públicas son el objetivo principal del departamento, este modulo sirve para monitorear cada una de ellas." ?>
<?php $modelo = "Obra"; ?>
<?php 
    $titulos = array(
    	"codigo" => "Código|100",
        "nombre" => "Nombre|400",
    	"localidades_id" => "Localidad|150",
        "fecha" => "Fecha|100",
    	"estado" => "Estado Actual|100"    	
    );
?>

<table class="formulario">
    <tr>
        <th width="1024" height="25" id="mensaje">
            &nbsp;
        </th>
    </tr>
    <tr>
        <td width="1024" height="205" id="contenido" align="center">
            <br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" style="width: 1000px;" align="left">
                    	<table border="0" width="1000">
                            <tr>
                                <td width="700">
                                    <h2 id="titulo">
                                        <?= $titulo ?>
                                    </h2>
                                    <span id="subtitulo">
                                    	<?= $subtitulo ?>
                                    </span>
                                    <br /><br />
                                </td>
                                <td width="50">
                                	<?= Html::link("escritorio/busquedaGeneral/".str_replace(" ","-",$busqueda)."/solicitudes","Solicitudes","class: ".($filtro == "solicitudes" ? "boton2" : "boton1")) ?>
                                </td>
                                <td width="50">
                                	<?= Html::link("escritorio/busquedaGeneral/".str_replace(" ","-",$busqueda)."/proyectos","Proyectos","class: ".($filtro == "proyectos" ? "boton2" : "boton1")) ?>
                                </td>
                                <td width="50">
                                	<?= Html::link("escritorio/busquedaGeneral/".str_replace(" ","-",$busqueda)."/obras","Obras","class: ".($filtro == "obras" ? "boton2" : "boton1")) ?>
                                </td>
                            </tr>
                        </table>
                        <?= Formulario::fin() ?>
                        <hr />
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr>
                <tr height="25">
                    <td colspan="7" align="center">                        
                            <table>
                                <tr id="encabezado">
                                	<th height="50" width="25" align="center"></th>	
                                    <?php if($titulos) foreach($titulos as $field => $value){ $titulo = substr($value,0,strpos($value,"|")); $tam = substr($value,strpos($value,"|")+1); ?>
							            <th width="<?= $tam ?>">
							            	<?= $titulo ?>
							            </th>
						            <?php } ?>
						             <th height="50" width="50" align="center">
						            	Avance
                                    </th>									
						            <th height="50" width="50" align="center">
						            	
                                    </th>
                                </tr>
                        <?php if($obras){ ?>
                            <?php $i=0; foreach($obras as $registro){ $i++; if($i%2==0) $x = "fila1"; else $x="fila2"; ?>
                                <tr id="<?= $x ?>">
									<td height="25" align="center">
                                	 	<?php $tmp = $registro -> presupuestado - $registro -> asignado ?>
                                	 	<?php if($tmp<=0){ ?>
                                	 		<?= Html::imagen("miniconos/flag_red.png","Presupuesto Excedido",15,15) ?>
                                	 	<?php } else { ?>
	                                	 	<?php if($registro -> presupuestado / 10 >= $tmp){ ?>
	                                	 		<?= Html::imagen("miniconos/flag_orange.png","Presupuesto Limitado",15,15) ?>
	                                	 	<?php } else { ?>
	                                	 		<?php if($registro -> presupuestado / 4 >= $tmp){ ?>
		                                	 		<?= Html::imagen("miniconos/flag_yellow.png","Presupuesto Reducido",15,15) ?>
		                                	 	<?php } else { ?>
		                                	 		<?= Html::imagen("miniconos/flag_blue.png","Presupuesto Amplio",15,15) ?>
		                                	 	<?php } ?>
	                                	 	<?php } ?>
                                	 	<?php } ?>
                                    </td>
                                    <td height="25" align="center">
                                        <?= $registro -> codigo ?>
                                    </td>
                                    <td height="25" align="center">
                                        <?= $registro -> nombre ?>
                                    </td>
                                    <td height="25" align="center">
                                        <?= $registro -> localidad() -> nombre ?>
                                    </td>
                                    <td height="25" align="center">
                                        <?= $registro -> fecha ?>
                                    </td>
                                    <td height="25" align="center" style="padding: 5px;">
                                    	<div id="estado<?= $registro -> id ?>">
                                    		<?php if(Acl::tienePermiso(Session::get("usuario_id"),"obras","programar")){ ?>
                                        		<?= Acl::linkAjax("obras/estado/".$registro -> id,$registro -> estado,"estado".$registro -> id,"style: color: #000; font-family: Verdana; font-size; 10px;") ?>
                                        	<?php } else { echo $registro -> estado; } ?>
                                        </div>
                                    </td>
                                    <td width="25" align="center">
                                    	<?= $registro -> porcentaje() ?>%
                                    </td>
                                    <td width="25" align="center">
                                    	<?= Acl::link("obras/consulta/".$registro -> id,Html::imagen("icons/preview.png","Consultar ".$modelo,20,20)) ?>
                                    </td>
                                </tr>
                            <?php } ?>
                        <?php } ?>
                        </table>
                    </td>
                </tr>
            </table>
            <br />
            <b>Número de Registros: <?= $nobras; ?></b>
            <br /><br />     
        </td>
    </tr>
</table>