<style type="text/css">
    body{
        background-color: #000000;
    }
</style>
<div style="text-align: center; margin: 50px; font-size: 12pt; font-family: Lucida Grande, Verdana, Sans-serif;">
	<table align="center" id="content" style="padding: 10px 10px 6px 10px; width: 50%;">
		<tbody>
			<tr>
				<td>
					<img src="<?php echo PUBLIC_PATH ?>img/amecasoft_logo.png" />
				</td>
				<td>
					<h1 style="font-size: 14pt; color: #990000; margin: 0 0 4px 0;">Página No Encontrada</h1>
				</td>
			</tr>
		</tbody>
	</table>
</div>