<?= Load::lib("amecasoft") ?>
<center>
	<?php $accion = Accion::buscar("controlador='".$controller_name."' AND accion='".$action_name."'") ?>
	<?php $recurso = $accion -> recurso(); ?>
	<?php $modulo = $recurso -> modulo(); ?>
	<div style='text-align: center; width: 50%; height: 110px; font-size: 28px; font-weight: bold;margin: 0 auto;padding: 2px 25px;background-repeat: no-repeat;background-position: 5px center;background-image: url("@path/img/error.gif"); background-color: #FDD;color: #B30000;border: 1px solid #FFB7B7;margin: 2px;' align="center"><br />ACCESO DENEGADO</div>
	<div style='text-align: center; width: 50%; height: 160px; font-size: 16px; font-weight: bold;margin: 0 auto;padding: 2px 25px;background-repeat: no-repeat;background-position: 5px center; background-image: url("@path/img/warning.gif");background-color: #FFFFC6;border: 1px solid #DD0;color: #000;' align="center">
		<br />
			No tienes el permiso para poder acceder a este recurso, por lo tanto el acceso ha sido denegado.
		<br />
		<br />
		<i><b>Módulo: </b><?= $modulo -> nombre ?></b></i>
		<br />
		<br />
		<i><b>Recurso: </b><?= $recurso -> nombre ?></b></i>
		<br />
		<br />
		<i><b>Controlador y Acción: </b><?= $controller_name ?>/<?= $action_name ?></b></i>
	</div>
</center>