<?php Load::lib("formato") ?>
<?php Load::lib("html") ?>
<?php Load::lib("aclx") ?>
<?php Load::lib("formulario") ?>
<?php $factura = IobrasFacturas::consultar($id) ?>
<?php $requisiciones = $factura -> requisiciones(); ?>
<style type="text/css">
	* {
		text-transform: uppercase;
	}
</style>

<div id="factura_desglozada">
	<table>
		<tr>
			<td>
				<table border="0" class="tabla">
					<tr>
						<td width="155" class="formato1">
							<b>RFC:</b>
						</td>
						<td width="155" class="formato4">
							<?= $factura -> rfc_emisor ?>
						</td>
						<td width="155" class="formato1">
							<b>No. Factura:</b>
						</td>
						<td width="155" class="formato4">
							<?= $factura -> numero_factura ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Proveedor:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $factura -> nombre_emisor ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Fecha:</b>
						</td>
						<td width="155" class="formato4">
							<?= Formato::fecha($factura -> fecha_emision) ?>
						</td>
						<td width="155" class="formato1">
							<b>Importe con IVA:</b>
						</td>
						<td width="155" class="formato4">
							$ <?= number_format($factura -> importe,2) ?>
						</td>
					</tr>
				</table>
			</td>
		</tr>
		<tr>
			<td height="10" align="center">
				<br />
				<?php if(isset($notificacion)){ ?>
				<div class="<?= $tipo_notificacion ?>" style="padding: 5px;">
					<?= $notificacion ?>
				</div>
				<?php } else { ?>
				<b style="font-size: 18px;">REQUISICIONES PARA ESTA FACTURA</b>
				<br />
				<?php } ?>
				<br />
			</td>
		</tr>
		<tr>
			<td>
				<?php if(isset($notificacion)){ ?>
					<div style="height: 316px; overflow: auto;">
				<?php } else { ?>
					<?php if($factura -> estado != "PAGADA" && $factura -> estado != "CANCELADA" && $factura -> obra() -> estado != "TERMINADA"){  ?>
						<div style="height: 348px; overflow: auto;">
					<?php } else { ?>
						<div style="height: 356px; overflow: auto;">
					<?php } ?>
				<?php } ?>	
					<div id="conceptos">
					<?= Formulario::inicioAjax("obras/agregarRequisicionFactura","factura_desglozada") ?>
					<?= Formulario::oculto("id",$factura -> id) ?>
					<table class="tabla">
						<tr>
							<th width="80" class="formato1">
								Fecha
							</th>
							<th width="300" class="formato1">
								Concepto
							</th>
							<th width="300" class="formato1">
								Elaboró
							</th>
							<th class="formato1"></th>
						</tr>
						<tr>
							<th class="formato4" colspan="3">
								<?= Formulario::autocompleteModelo("requisicion".$factura -> id,IobrasRequisiciones::reporte("obras_id=".$factura -> obras_id),"concepto","","style: width: 600px;","validate: required:true") ?>
							</th>
							<td class="formato4">
								<?= Formulario::imagen("Agregar Requisicion","miniconos/add.png") ?>
							</td>
						</tr>
						<?php if($requisiciones) foreach($requisiciones as $requisicion){ ?>
						<tr>
							<td width="75" align="center" class="formato4">
								<?= Formato::fecha($requisicion -> fecha) ?>
							</td>
							<td width="340" align="center" class="formato4">
								<?= $requisicion -> concepto ?>
							</td>
							<td width="100" align="center" class="formato4"> 
								<?= $requisicion -> elaboro() ? $requisicion -> elaboro() -> nombre : "" ?>
							</td>
							<td class="formato4" align="center" valign="middle">
								<?php $tmp = IobrasFacturarequisicion::consultar("requisicion_id=".$requisicion -> id." AND factura_id=".$factura -> id); ?>
								<?= Acl::linkAjaxConfirmado("obras/eliminarRequisicionFactura/".$tmp -> id,Html::imagen("miniconos/delete.png","Descartar Factura",18,18),"factura_desglozada","") ?>
							</td>
						</tr> 
						<?php } ?>
					</table>
					<?= Formulario::fin() ?>
					</div>
				</div>
			</td>
		</tr>
	</table>
</div>