<?= Load::lib("amecasoft") ?>
<table>
    <tr>
        <td class="formato1" width="365" height="25" ><br/>
            <center><?= View::partial("menuObra",false,array("obra" => $obra -> id,"opcion" => "avances")) ?></center>
        </td>
    </tr>
    <tr>
        <td class="formato2"><br />
            <center><?= View::partial("menuSupervisionObra",false,array("obra" => $obra -> id,"opcion" => "incidencias")) ?></center>
        </td>
    </tr>
</table>
<?= Formulario::inicioAjax("obras/registrarIncidencia","opciones") ?>
<input type="hidden" name="obra_id" value="<?= $obra -> id ?>" />
<table class="formulario" height="948">
    
    <tr>
        <td width="350" id="contenido" align="center" valign="top">
            <br />
            <table border="0" cellpadding="0" cellspacing="0">
                <tr height="25">
                    <td colspan="7" width="320"align="left">
                        <h2 id="titulo">
                        	Incidencias de la Obra                        	
                        </h2>
                        <span id="subtitulo">
                            La incidencias nos ayudaran a monitorear el progreso de la Obra.
                        </span>                        
                    </td>
                </tr>
                <tr>
                    <td colspan="7" height="10"></td>
                </tr> 
                	<?php if(Acl::tienePermiso(Session::get("usuario_id"),"obras","registrarIncidencia") && $obra -> estado != "TERMINADA"){ ?>
                <tr>
                    <td colspan="7" height="10"><br /><hr /><br/></td>
                </tr>
                <tr>
                    <td colspan="7" height="10" align="center" bgcolor="DDDDDD" style="padding: 5px;">
						<table border="0">
							<tr>
			                    <td>
			                        <div id="texto_arriba">Fecha <span id="asterisco">*</span></div>
			                        <?= Formulario::fecha("fecha","","dd/mm/yy",false,false,"class: fchico","style: width: 300px;","validate: required:true") ?>
			                    </td>			                   
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>                                       
			                <tr>
			                    <td>
			                        <div id="texto_arriba">Descripción de Actividades <span id="asterisco">*</span></div>
			                        <?= Formulario::textarea("descripcion","","style: width: 307px; height: 70px;","validate: required:true") ?>
			                    </td>
			                </tr>
			                <tr>
			                    <td>
			                        <div id="texto_arriba">Reporta la Incidencia: <span id="asterisco">*</span></div>
			                        <?php $empleados = Empleado::reporte('id > 0','nombre ASC') ?>
			                        <?= Formulario::selectModelo('empleado_id',$empleados,'nombre','id','','style: width: 300px;') ?>
			                    </td>			                   
			                </tr>
			                <tr>
			                    <td height="10"></td>
			                </tr>
			                <tr>
			                    <td height="25" align="right">
			                        <?= Formulario::submit("Registrar Incidencia","class: boton1") ?>
			                    </td>
			                </tr>			                
						</table>
					</td>
                </tr>
                <?php } ?>  
                <tr>
                    <td colspan="7" height="10">
                    	<br />
                        <hr />
                        <br />
                    </td>
                </tr>                                    
                <tr>
			    	<td colspan="7" height="10">
			        	<?php $avances = $obra -> incidencias(); $n = count($avances); ?>
			            <?php if($avances){ ?>
				        	<table border="0">
				            	<?php $x=0; foreach($avances as $avance){ $x++; ?>
				            		<?= tr_color("#CCCCCC","#CCCCCC","#DDDDDD","#DDDDDD") ?>				                    	
				                    	<td style="padding: 5px;" width="275" align="center"><?= fechaExtendida($avance -> fecha) ?></td>
					                    <td style="padding: 5px 10px;" align="center">					                    	
					                    	<?php if($obra -> estado != "TERMINADA"){ ?>
					                    		<?= Acl::linkAjaxConfirmado("obras/eliminarIncidencia/".$avance -> id,Html::imagen("miniconos/delete.png","Eliminar Avance",15,15),"opciones","Estas seguro que deseas eliminar el Avance?") ?>
					                    	<?php } ?>
					                    </td>
									</tr>
									<?= tr_color("#CCCCCC","#CCCCCC","#DDDDDD","#DDDDDD") ?>
										<td colspan="2" style="padding: 5px; text-align: center; font-weight: bold;">
											<?= $avance -> empleado(); ?>											
										</td>
									</tr>
									<?= tr_color("#CCCCCC","#CCCCCC","#DDDDDD","#DDDDDD") ?>
										<td colspan="2" height="50" style="padding: 5px;">
											<div align="justify" style="font-size: 10px; padding: 5px;">
												<?= $avance -> descripcion ?>
											</div>
										</td>
									</tr>
									<?php if($x<$n){ ?>
									<tr>
										<td colspan="3">&nbsp;</td>
									</tr>
									<?php } ?>
				            	<?php } ?>
							</table>
				        <?php } else { ?>
				        	<center><b>NO SE HAN AGREGADO INCIDENCIAS</b></center>
				        <?php } ?>
					</td>
			   	</tr>			   
            </table>
            <br />    
        </td>
    </tr>
</table>
<?= Formulario::fin() ?>
</div>