<?php Load::lib("formato") ?>
<?php Load::lib("html") ?>
<?php Load::lib("aclx") ?>
<?php Load::lib("formulario") ?>
<?php $requisicion = IobrasRequisiciones::consultar($id) ?>
<?php $facturas = $requisicion -> facturas(); ?>
<style type="text/css">
	* {
		text-transform: uppercase;
	}
</style>

<div id="factura_desglozada">
	<table>
		<tr>
			<td>
				<table border="0" class="tabla">
					<tr>
						<td width="155" class="formato1">
							<b>Fecha:</b>
						</td>
						<td width="155" class="formato4">
							<?= Formato::fecha($requisicion -> fecha) ?>
						</td>
						<td width="155" class="formato1">
							<b>Estado Actual:</b>
						</td>
						<td width="155" class="formato4">
							<?= $requisicion -> estado ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Supervisor:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> supervisor()? $requisicion -> supervisor() -> nombre : "" ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Elaboró:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> elaboro() ? $requisicion -> elaboro() -> nombre : "" ?>
						</td>
					</tr>
					<?php if($requisicion -> estado == "AUTORIZADA"){ ?>
					<tr>
						<td width="155" class="formato1">
							<b>Autorizó:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> autorizo() ? $requisicion -> autorizo() -> nombre : "NO HA SIDO AUTORIZADA" ?>
						</td>
					</tr>
					<?php } ?>
				</table>
			</td>
		</tr>
		<tr>
			<td height="10" align="center">
				<br />
				<?php if(isset($notificacion)){ ?>
				<div class="<?= $tipo_notificacion ?>" style="padding: 5px;">
					<?= $notificacion ?>
				</div>
				<?php } else { ?>
				<b style="font-size: 18px;">FACTURAS PARA ESTA REQUISICIÓN</b>
				<br />
				<?php } ?>
				<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){  ?>
				<br />
				<?php } ?>
			</td>
		</tr>
		<tr>
			<td>
				<?php if(isset($notificacion)){ ?>
					<div style="height: 316px; overflow: auto;">
				<?php } else { ?>
					<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){  ?>
						<div style="height: 348px; overflow: auto;">
					<?php } else { ?>
						<div style="height: 356px; overflow: auto;">
					<?php } ?>
				<?php } ?>	
					<div id="conceptos">
					<?= Formulario::inicioAjax("obras/agregarFacturaRequisicion","factura_desglozada") ?>
					<?= Formulario::oculto("id",$requisicion -> id) ?>
					<table class="tabla">
						<tr>
							<th width="80" class="formato1">
								Fecha
							</th>
							<th width="500" class="formato1">
								Emisor
							</th>
							<th width="100" class="formato1">
								Importe
							</th>
							<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
								<th class="formato1"></th>
							<?php } ?>	
						</tr>
						<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
						<tr>
							<th class="formato4" colspan="3">
								<?= Formulario::autocompleteModelo("factura".$requisicion -> id,IobrasFacturas::reporte("obras_id=".$requisicion -> obras_id),"nombre_emisor","","style: width: 600px;","validate: required:true") ?>
							</th>
							<td class="formato4">
								<?= Formulario::imagen("Agregar Factura","miniconos/add.png") ?>
							</td>
						</tr>
						<?php } ?>
						<?php if($facturas) foreach($facturas as $factura){ ?>
						<tr>
							<td width="75" align="center" class="formato4">
								<?= Formato::fecha($factura -> fecha_emision) ?>
							</td>
							<td width="340" align="center" class="formato4">
								<?= $factura -> nombre_emisor ?>
							</td>
							<td width="100" align="right" class="formato4">
								<?= Formato::dinero($factura -> importe) ?>
							</td>
							<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
							<td class="formato4" align="center" valign="middle">
								<?php $tmp = IobrasFacturarequisicion::consultar("requisicion_id=".$requisicion -> id." AND factura_id=".$factura -> id); ?>
								<?= Acl::linkAjaxConfirmado("obras/eliminarFacturaRequisicion/".$tmp -> id,Html::imagen("miniconos/delete.png","Descartar Factura",18,18),"factura_desglozada","") ?>
							</td>
							<?php } ?>
						</tr> 
						<?php } ?>
					</table>
					<?= Formulario::fin() ?>
					</div>
				</div>
			</td>
		</tr>
	</table>
</div>