<?php Load::lib("formato") ?>
<?php Load::lib("html") ?>
<?php Load::lib("aclx") ?>
<?php Load::lib("formulario") ?>
<?php $requisicion = IobrasRequisiciones::consultar($id) ?>
<?php $conceptos = $requisicion -> conceptos(); ?>
<?php $productos = Insumo::reporte('id > 0', 'nombre ASC'); ?>
<?php
	if($productos) foreach($productos as $producto){
		$producto -> nombre = $producto -> nombre . ' {'.$producto -> medida.'}';
	}
?>
<style type="text/css">
	* {
		text-transform: uppercase;
	}
</style>

<div id="factura_desglozada">
	<table>
		<tr>
			<td>
				<table border="0" class="tabla">
					<tr>
						<td width="155" class="formato1">
							<b>Fecha:</b>
						</td>
						<td width="155" class="formato4">
							<?= Formato::fecha($requisicion -> fecha) ?>
						</td>
						<td width="155" class="formato1">
							<b>Estado Actual:</b>
						</td>
						<td width="155" class="formato4">
							<?= $requisicion -> estado ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Supervisor:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> supervisor()? $requisicion -> supervisor() -> nombre : "" ?>
						</td>
					</tr>
					<tr>
						<td width="155" class="formato1">
							<b>Elaboró:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> elaboro() ? $requisicion -> elaboro() -> nombre : "" ?>
						</td>
					</tr>
					<?php if($requisicion -> estado == "AUTORIZADA"){ ?>
					<tr>
						<td width="155" class="formato1">
							<b>Autorizó:</b>
						</td>
						<td colspan="3" class="formato4">
							<?= $requisicion -> autorizo() ? $requisicion -> autorizo() -> nombre : "NO HA SIDO AUTORIZADA" ?>
						</td>
					</tr>
					<?php } ?>
				</table>
			</td>
		</tr>
		<tr>
			<td height="10">
				<br />
				<?php if(isset($notificacion)){ ?>
				<div class="success_message" style="padding: 5px;">
					<?= $notificacion ?>
				</div>
				<?php } ?>
			</td>
		</tr>
		<tr>
			<td>
				<?= Formulario::inicioAjax("obras/agregarConceptoRequisicion","factura_desglozada") ?>
					<?= Formulario::oculto("id",$requisicion -> id) ?>
					<table class="tabla">
						<tr>
							<th width="80" class="formato1">
								Cantidad
							</th>
							<th width="525" class="formato1">
								Concepto
							</th>
							<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
								<th class="formato1"></th>
							<?php } ?>	
						</tr>
						<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
						<tr>
							<th width="80" class="formato4">
								<?= Formulario::numerico("cantidad".$requisicion -> id,"","style: text-align: center; width:75px;","validate: required:true") ?>
							</th>
							<th width="525" class="formato4">
								<?= Formulario::autocompleteModelo("concepto".$requisicion -> id,$productos,"nombre","","style: width: 500px;","validate: required:true") ?>
							</th>
							<td class="formato4">
								<?= Formulario::imagen("Agregar Concepto","miniconos/add.png") ?>
							</td>
						</tr>
						<?php } ?>
					</table>
					<?= Formulario::fin() ?>
					<br />
				<?php if(isset($notificacion)){ ?>
					<div style="height: 246px; overflow: auto;">
				<?php } else { ?>
					<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){  ?>
						<div style="height: 278px; overflow: auto;">
					<?php } else { ?>
						<div style="height: 286px; overflow: auto;">
					<?php } ?>
				<?php } ?>
					<div id="conceptos">
					<table class="tabla">
						<tr>
							<th width="80" class="formato1">
								Cantidad
							</th>
							<th width="525" class="formato1">
								Concepto
							</th>
							<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
								<th class="formato1"></th>
							<?php } ?>	
						</tr>
						<?php if($conceptos) foreach($conceptos as $concepto){ ?>
						<tr>
							<td width="75" align="center" class="formato4">
								<?= $concepto -> cantidad ?>
							</td>
							<td width="<?= ($requisicion -> estado == "PAGADA" || $requisicion -> estado == "CANCELADA") ? 340 : 325 ?>" align="center" class="formato4">
								<?= $concepto -> insumo() -> medida ?> de <?= $concepto -> insumo() -> nombre ?>
							</td>
							<?php if($requisicion -> estado != "PAGADA" && $requisicion -> estado != "CANCELADA" && $requisicion -> obra() -> estado != "TERMINADA"){ ?>
							<td class="formato4" align="center" valign="middle">
								<?= Acl::linkAjaxConfirmado("obras/eliminarConceptoRequisicion/".$concepto -> id,Html::imagen("miniconos/delete.png","Eliminar Concepto",18,18),"factura_desglozada","") ?>
							</td>
							<?php } ?>
						</tr> 
						<?php } ?>
					</table>
					</div>
				</div>
			</td>
		</tr>
	</table>
</div>